baseURL = "https://akshaybk.com/"
languageCode = "en-us"
title = "Akshay B.K — DevOps Engineer"
theme = "PaperMod"

[params]
  author = "Akshay B.K"
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"
[menu]

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    name = "Jobs"
    url = "/jobs/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 4

